In [1]:
%reload_ext autoreload
%autoreload 2

In [1]:
from datasets import load_dataset
from huggingface_hub import hf_hub_download
import json
import pandas as pd


dataset = load_dataset("nasa-impact/nasa-smd-IR-benchmark")
val_df = dataset["validation"].to_pandas()
test_df = dataset["test"].to_pandas()

# Download queries.jsonl from the dataset repo
queries_path = hf_hub_download(
    repo_id="nasa-impact/nasa-smd-IR-benchmark",
    filename="queries.jsonl",
    repo_type="dataset"
)

# Download corpus.jsonl similarly
corpus_path = hf_hub_download(
    repo_id="nasa-impact/nasa-smd-IR-benchmark",
    filename="corpus.jsonl",
    repo_type="dataset"
)

queries_df = pd.read_json(queries_path, lines=True)
queries_df.rename(columns={"_id": "query-id", "text": "query"}, inplace=True)

corpus_df = pd.read_json(corpus_path, lines=True)
corpus_df.rename(columns={"_id": "corpus-id", "text": "corpus"}, inplace=True)

# Join for validation set
val_df = val_df.merge(queries_df, on="query-id", how="left")
val_df = val_df.merge(corpus_df, on="corpus-id", how="left")

# Join for test set
test_df = test_df.merge(queries_df, on="query-id", how="left")
test_df = test_df.merge(corpus_df, on="corpus-id", how="left")

In [34]:
val_df

,query-id,corpus-id,score,query,title,corpus
0,67,72915,1,What does the Mann-Kendall test do?,,Apart from groundwater mentioned in the above ...
1,239,37223,1,What complicates the theory of the observer?,,Every careful observer of this magnificent pla...
2,495,250048,1,What are the two mechanisms regarding the move...,,We present a novel mathematical formalism to p...
3,283,125841,1,"Can solid monolithic ""rocky"" bodies shed a dus...",,"Related to the morphology, it is the tensile s..."
4,200,213374,1,Besides being born in or from a circumplanetar...,,The low orbital inclinations of Phobos and Dei...
...,...,...,...,...,...,...
95,61,18475,1,The equilibrium models and some dynamic vegeta...,,It is likely that changing temperature and pre...
96,197,115182,1,What surface and thermodynamical processes are...,,"Recently, numerically sophisticated general ci..."
97,81,198092,1,AN pollution in mine soil is becoming a seriou...,,The problem of AN pollution in mine soil is be...
98,249,118331,1,Over what wavelength range was IRIS used to ob...,,"At longer wavelengths, Miranda and Ariel were ..."
99,133,34741,1,Which instrument is on the Suomi National Pola...,,We present a near surface air temperature (NSA...

In [2]:
corpus_df

        corpus-id title                                             corpus
0               0        We find the general solution to the twisting e...
1               1        The black hole binary Cygnus X-1 was observed ...
2               2        The two galactic `microquasars' with superlumi...
3               3        A program has been developed to provide for th...
4               4        The authors have studied membership and duplic...
...           ...   ...                                                ...
270201     270201        In this paper we study holomorphic rank two ve...
270202     270202        A phenomenological description of the neutral ...
270203     270203        Four high velocity southern stars and one Popu...
270204     270204        Computer simulations are used to describe the ...
270205     270205        We develop a simple method to determine the ac...

[270206 rows x 3 columns]