In [2]:
%reload_ext autoreload
%autoreload 2

In [3]:
import pandas as pd

data_path = "/rhome/sawale/indus_traning/mlm-fine-tuning/mlm/data/cleaned_prod_dump_filtered_word_count_yake.parquet"

df = pd.read_parquet(data_path, )

df

,id,url1,title,collection,treepath,sourcestr56,old_text,sourcebool3,text,yake
0,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/data/,ACTIVATE: Data – NASA Langley Research Center...,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Data,ACTIVATE: Data - NASA Langley Research Center ...,False,ACTIVATE: Data - NASA Langley Research Center ...,"[[""FLIGHTS"", 0.0025156622989489638], [""ACTIVAT..."
1,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/,ACTIVATE: Home – NASA Langley Research Center ...,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Documentation,ACTIVATE: Home - NASA Langley Research Center ...,False,ACTIVATE: Home - NASA Langley Research Center ...,"[[""FLIGHTS"", 0.0024120919674993795], [""ACTIVAT..."
2,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/media/,ACTIVATE: Media – NASA Langley Research Cente...,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Documentation,ACTIVATE: Media - NASA Langley Research Center...,False,ACTIVATE: Media - NASA Langley Research Center...,"[[""FLIGHTS"", 0.002483062973658925], [""ACTIVATE..."
3,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/instrum...,ACTIVATE: Instruments – NASA Langley Research ...,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Missions and Instruments,ACTIVATE: Instruments - NASA Langley Research ...,False,ACTIVATE: Instruments - NASA Langley Research ...,"[[""FLIGHTS"", 0.002533450856132368], [""ACTIVATE..."
4,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/education/,ACTIVATE: Education – NASA Langley Research C...,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Documentation,ACTIVATE: Education - NASA Langley Research Ce...,False,ACTIVATE: Education - NASA Langley Research Ce...,"[[""FLIGHTS"", 0.002482532509504613], [""CLOUD"", ..."
...,...,...,...,...,...,...,...,...,...,...
545712,/SDE/PDS_API_Legacy_All/|572678ad19f76c25fed20...,None,"Mars 2020 Navigation Cameras Bundle, raw products",/SDE/PDS_API_Legacy_All/,/Planetary Science/Planetary Science Data (PDS)/,None,"‮⁤‭\n\nMars 2020 Navigation Cameras Bundle, ra...",False,"Mars 2020 Navigation Cameras Bundle, raw products","[[""NAVIGATION"", 0.1447773057422032], [""CAMERAS..."
545713,/SDE/PDS_API_Legacy_All/|f4ad33d01942edb2aff31...,None,Mars 2020 Mast Camera Zoom Bundle,/SDE/PDS_API_Legacy_All/,/Planetary Science/Planetary Science Data (PDS)/,None,‮⁤‭\n\nMars 2020 Mast Camera Zoom Bundle\n\n,False,Mars 2020 Mast Camera Zoom Bundle,"[[""BUNDLE"", 0.08596317751626563], [""MAST"", 0.1..."
545714,/SDE/PDS_API_Legacy_All/|f6f145cf2776c82baa6ed...,None,"Mars 2020 Hazard Cameras Bundle, mosaic products",/SDE/PDS_API_Legacy_All/,/Planetary Science/Planetary Science Data (PDS)/,None,"‮⁤‭\n\nMars 2020 Hazard Cameras Bundle, mosaic...",False,"Mars 2020 Hazard Cameras Bundle, mosaic products","[[""HAZARD"", 0.1447773057422032], [""CAMERAS"", 0..."
545715,/SDE/PDS_API_Legacy_All/|4bb7b0611d08b4a4acddf...,None,Mars Science Laboratory Mastcam MAHLI MARDI (M...,/SDE/PDS_API_Legacy_All/,/Planetary Science/Planetary Science Data (PDS)/,None,‮⁤‭\n\nMars Science Laboratory Mastcam MAHLI M...,False,Mars Science Laboratory Mastcam MAHLI MARDI (M...,"[[""BUNDLE"", 0.08596317751626563], [""SCIENCE"", ..."
545716,/SDE/PDS_API_Legacy_All/|c52d10c3b494af9cb4cf7...,None,PDS4 Context Products,/SDE/PDS_API_Legacy_All/,/Planetary Science/Planetary Science Data (PDS)/,None,‮⁤‭\n\nPDS4 Context Products\n\n,False,PDS4 Context Products,"[[""PDS4"", 0.08596317751626563], [""PRODUCTS"", 0..."

# CMR

In [16]:
from collections import Counter

# df[df["collection"] == "/SDE/CMR_API/"]

df[df["id"].str.startswith("/SDE/CMR_API/")]

,id,url1,title,collection,treepath,sourcestr56,old_text,sourcebool3,text,yake
484748,/SDE/CMR_API/|C2789815280-ENVIDAT,None,'Latent reserves' within the Swiss NFI,/SDE/CMR_API/,/Earth Science/Earth Science Data (CMR)/,Data,‮⁤‭ \n\n\nlatent-reserves-in-the-swiss-nfiThe ...,False,latent-reserves-in-the-swiss-nfiThe files refe...,"[[""DATA"", 0.02868194383493252], [""SWISS"", 0.03..."
484749,/SDE/CMR_API/|C1214305813-AU_AADC,None,0.5 hour 1 M HCl extraction data for the Windm...,/SDE/CMR_API/,/Earth Science/Earth Science Data (CMR)/,Data,‮⁤‭ \n\n\nASAC_2201_HCL_0.5These results are f...,False,ASAC_2201_HCL_0.5These results are for the 0.5...,"[[""EXTRACTION"", 0.03316665101660428], [""HCL"", ..."
484750,/SDE/CMR_API/|C2207472890-FEDEO,None,10 Days Synthesis of SPOT VEGETATION Images (V...,/SDE/CMR_API/,/Earth Science/Earth Science Data (CMR)/,Data,‮⁤‭ \n\n\nurn:ogc:def:EOP:VITO:VGT_S10The VGT-...,False,urn:ogc:def:EOP:VITO:VGT_S10The VGT-S10 are ne...,"[[""EOP"", 0.06992420630200866], [""VITO"", 0.0699..."
484751,/SDE/CMR_API/|C1214313574-AU_AADC,None,10 m firn temperature data: LGB traverses 1990-95,/SDE/CMR_API/,/Earth Science/Earth Science Data (CMR)/,Data,‮⁤‭ \n\n\nLGB_10m_traverseThe Lambert Glacier ...,False,LGB_10m_traverseThe Lambert Glacier Basin (LGB...,"[[""DATA"", 0.08625732750120468], [""STATION"", 0...."
484752,/SDE/CMR_API/|C1214305884-AU_AADC,None,10 year trend of levels of organochlorine poll...,/SDE/CMR_API/,/Earth Science/Earth Science Data (CMR)/,Data,‮⁤‭ \n\n\nASAC_2357Metadata record for data fr...,False,ASAC_2357Metadata record for data from ASAC Pr...,"[[""LENGTH"", 0.026029089681482563], [""DATA"", 0...."
...,...,...,...,...,...,...,...,...,...,...
538215,/SDE/CMR_API/|C2089375330-NOAA_NCEI,None,"Zooplankton, oceanographic profile, and other ...",/SDE/CMR_API/,/Earth Science/Earth Science Data (CMR)/,Data,‮⁤‭ \n\n\ngov.noaa.nodc:0000499This dataset is...,False,gov.noaa.nodc:0000499This dataset is available...,"[[""OCEAN"", 0.026210680222717775], [""ANTARCTIC""..."
538216,/SDE/CMR_API/|C2089381193-NOAA_NCEI,None,"Zooplankton, chemical, and other data collecte...",/SDE/CMR_API/,/Earth Science/Earth Science Data (CMR)/,Data,‮⁤‭ \n\n\ngov.noaa.nodc:7200691This dataset is...,False,gov.noaa.nodc:7200691This dataset is available...,"[[""GREAT"", 0.05985648920523849], [""LAKES"", 0.0..."
538217,/SDE/CMR_API/|C2089375494-NOAA_NCEI,None,"Zooplankton, temperature, salinity, and nutrie...",/SDE/CMR_API/,/Earth Science/Earth Science Data (CMR)/,Data,‮⁤‭ \n\n\ngov.noaa.nodc:0000527This dataset is...,False,gov.noaa.nodc:0000527This dataset is available...,"[[""PACIFIC"", 0.055133853423971084], [""DATA"", 0..."
538218,/SDE/CMR_API/|C2089386429-NOAA_NCEI,None,"Zooplankton, chemical, and other data collecte...",/SDE/CMR_API/,/Earth Science/Earth Science Data (CMR)/,Data,‮⁤‭ \n\n\ngov.noaa.nodc:9800109This dataset is...,False,gov.noaa.nodc:9800109This dataset is available...,"[[""ZOOPLANKTON"", 0.08400519114560805], [""DATA""..."
538219,/SDE/CMR_API/|C2089373573-NOAA_NCEI,None,"Zooplankton, salinity, and other data from the...",/SDE/CMR_API/,/Earth Science/Earth Science Data (CMR)/,Data,‮⁤‭ \n\n\ngov.noaa.nodc:0000262This dataset is...,False,gov.noaa.nodc:0000262This dataset is available...,"[[""DATA"", 0.10587161031529181], [""1999"", 0.121..."

In [25]:
from collections import Counter

pds = {k: v for k, v in dict(Counter([x[1] + "/" + x[2] for x in df["treepath"].str.split("/").to_list()])).items() if k.startswith("Planetary")}

sorted(pds.items(), key=lambda item: item[1], reverse=True)

[('Planetary Science/Photojournal', 24368),
 ('Planetary Science/MASTCAM-Z', 19844),
 ('Planetary Science/NASA Science', 16835),
 ('Planetary Science/Mission Juno', 15673),
 ('Planetary Science/Gazetteer of Planetary Nomenclature', 12225),
 ('Planetary Science/Astrobiology at NASA', 10833),
 ('Planetary Science/Planetary Science Data (PDS)', 6966),
 ('Planetary Science/NASA Space Science Data Coordinated Archive (NSSDCA)',
  2115),
 ('Planetary Science/Lunar Reconnaissance Orbiter Camera (LROC)', 2000),
 ('Planetary Science/Archive Navigator', 1820),
 ('Planetary Science/Astropedia: Lunar and Planetary Cartographic Catalog',
  1633),
 ('Planetary Science/Jet Propulsion Laboratory (JPL)', 1509),
 ('Planetary Science/Apollo Lunar Surface Journal', 1232),
 ('Planetary Science/Johnson Space Center History Portal', 1001),
 ('Planetary Science/OSIRIS-REx Asteroid Sample Return Mission', 897),
 ('Planetary Science/ILRS: International Laser Ranging Service', 797),
 ('Planetary Science/Orbital Data Explorer', 606),
 ('Planetary Science/Europa Clipper', 551),
 ('Planetary Science/Asteroid Radar Research', 463),
 ('Planetary Science/PDS Geosciences Node', 447),
 ('Planetary Science/Science at GSFC', 441),
 ('Planetary Science/IAU Minor Planet System', 315),
 ('Planetary Science/PDS Ring Moon Systems Node', 310),
 ('Planetary Science/Astromaterials Acquisition and Curation Office', 307),
 ('Planetary Science/Solar System Exploration Division', 248),
 ('Planetary Science/Navigation and Ancillary Information Facility (NAIF)',
  218),
 ("Planetary Science/NASA Science Earth's Moon", 186),
 ('Planetary Science/Center for Near Earth Object Studies (CNEOS)', 174),
 ('Planetary Science/Lucy Mission', 161),
 ('Planetary Science/Planetary Data System (PDS)', 142),
 ('Planetary Science/New Frontiers', 135),
 ('Planetary Science/Radio JOVE', 130),
 ('Planetary Science/PDS Planetary Atmospheres Node', 129),
 ('Planetary Science/PDS Cartography and Imaging Sciences Node', 116),
 ('Planetary Science/Solar System Dynamics', 115),
 ('Planetary Science/Planetary Plasma Interactions (PPI) Node', 95),
 ('Planetary Science/Christensen Research Group', 95),
 ('Planetary Science/Lunar Trailblazer', 90),
 ('Planetary Science/Sungrazer Project', 87),
 ('Planetary Science/PDS Small Bodies Node', 86),
 ('Planetary Science/NSPIRES: NASA Solicitation and Proposal Integrated Review and Evaluation System',
  80),
 ('Planetary Science/Solar System Exploration Research Virtual Institute (SSERVI)',
  70),
 ('Planetary Science/Astromaterials Data System', 52),
 ('Planetary Science/Explorer-1', 45),
 ('Planetary Science/PDS Small Bodies Node Asteroid Dust Subnode', 44),
 ('Planetary Science/NASA Solar System Treks', 43),
 ('Planetary Science/Escape and Plasma Acceleration and Dynamics Explorers (ESCAPADE)',
  32),
 ('Planetary Science/Lowell Minor Planet Services', 30),
 ('Planetary Science/PDS Geosciences Node Spectral Library', 27),
 ('Planetary Science/Astrogeology Analysis Ready Data', 26),
 ('Planetary Science/Voyager', 25),
 ('Planetary Science/ShadowCam', 22),
 ('Planetary Science/Small Bodies Image Browser', 15),
 ('Planetary Science/NASA Ames Intelligent Systems Division Data', 14),
 ('Planetary Science/Asteroid Lightcurve Photometry Database (ALCDEF)', 10),
 ("Planetary Science/F' (F Prime)", 9),
 ('Planetary Science/NASA Planetary Sciences at PBS', 6),
 ('Planetary Science/Mars Target Encyclopedia (MTE)', 3),
 ('Planetary Science/COMET ASTEROID TELESCOPIC CATALOG HUNTER', 3),
 ('Planetary Science/Planetary Image Locator Tool (PILOT)', 2),
 ('Planetary Science/PDS Data Dictionary Search', 1),
 ('Planetary Science/ISIS: Integrated Software for Imagers and Spectrometers',
  1),
 ('Planetary Science/PDS4 Local Data Dictionary Tool', 1),
 ('Planetary Science/TES Data Tool', 1),
 ("Planetary Science/Analyst's Notebook", 1),
 ('Planetary Science/Java Mission-planning and Analysis for Remote Sensing (JMARS)',
  1),
 ('Planetary Science/PDS4 JParser', 1),
 ("Planetary Science/NASA's Eyes", 1)]

In [22]:
cmr = df[df["treepath"].str.startswith("/Earth Science/Earth Science Data (CMR)")]

print(cmr[["id", "url1", "title", "collection", "treepath", "sourcestr56", "sourcebool3", "text"]].head(1).to_json(orient="records", indent=2))

[
  {
    "id":"\/SDE\/CMR_API\/|C2789815280-ENVIDAT",
    "url1":null,
    "title":"'Latent reserves' within the Swiss NFI",
    "collection":"\/SDE\/CMR_API\/",
    "treepath":"\/Earth Science\/Earth Science Data (CMR)\/",
    "sourcestr56":"Data",
    "sourcebool3":false,
    "text":"latent-reserves-in-the-swiss-nfiThe files refer to the data used in Portier et al. \"\u2018Latent reserves': a hidden treasure in National Forest Inventories\" (2020) *Journal of Ecology*. **'Latent reserves'** are defined as plots in National Forest Inventories (NFI) that have been free of human influence for >40 to >70 years. They can be used to investigate and acquire a deeper understanding of attributes and processes of near-natural forests using existing long-term data. To determine which NFI sample plots could be considered \u2018latent reserves', criteria were defined based on the information available in the Swiss NFI database: * Shrub forests were excluded. * Plots must have been free of any kind of management, including salvage logging or sanitary cuts, for a minimum amount of time. Thresholds of 40, 50, 60 and 70 years without intervention were tested. * To ensure that species composition was not influenced by past management, plots where potential vegetation was classified as deciduous by Ellenberg & Kl\u00f6tzli (1972) had to have an observed proportion of deciduous trees matching the theoretical proportion expected in a natural deciduous forest, as defined by Kienast, Brzeziecki, & Wildi (1994). * Plots had to originate from natural regeneration. * Intensive livestock grazing must never have occurred on the plots. The tables stored here were derived from the first, second and third campaigns of the Swiss NFI. The raw data from the Swiss NFI can be provided free of charge within the scope of a contractual agreement (http:\/\/www.lfi.ch\/dienstleist\/daten-en.php). **** The files 'Data figure 2' to 'Data figure 8' are publicly available and contain the data used to produce the figures published in the paper. The files 'Plot-level data for characterisation of 'latent reserves' and 'Tree-level data for characterisation of 'latent reserves' contain all the data required to reproduce the section of the article concerning the characterisation of 'latent reserves' and the comparison to managed forests. The file 'Data for mortality analyses' contains the data required to reproduce the section of the article concerning tree mortality in 'latent reserves'. The access to these three files is restricted as they contain some raw data from the Swiss NFI, submitted to the Swiss law and only accessible upon contractual agreement.\nSwiss Federal Institute for Forest, Snow and Landscape Research WSL\nFOREST SCIENCE;FOREST RESERVES;NATIONAL FOREST INVENTORY;NEAR-NATURAL FOREST;SWITZERLAND;TREE MORTALITY\n'Latent reserves' within the Swiss NFI"
  }
]

In [35]:
df[df["treepath"].str.contains("PDS")]["collection"].value_counts()

collection
/SDE/PDS_API_Legacy_All/                                         6966
/SDE/Geosciences_Node/                                            447
/SDE/pds_rings/                                                   310
/SDE/pds_website/                                                 142
/SDE/pds_atmospheres/                                             129
/SDE/pds_cartography_and_imaging_sciences_node/                   116
/SDE/Small_Bodies_Node/                                            86
/SDE/PDS_PDS_Small_Bodies_Node_Asteroid_Dust_Subnode_Website/      44
/SDE/pds_geosciences_node_spectral_library/                        27
/SDE/PDS_Data_Dictionary_Search/                                    1
/SDE/PDS_PDS4_JParser_Website/                                      1
/SDE/PDS_PDS4_Local_Data_Dictionary_Tool_Website/                   1
Name: count, dtype: int64

In [50]:
pds = df[df["collection"].str.contains("/SDE/PDS_API_Legacy_All/")]

pds.head()

,id,url1,title,collection,treepath,sourcestr56,old_text,sourcebool3,text,yake
538751,/SDE/PDS_API_Legacy_All/|f25862eed648d0ce58521...,None,ROSETTA-ORBITER 67P RSI 1/2/3 COMET ESCORT 3 1...,/SDE/PDS_API_Legacy_All/,/Planetary Science/Planetary Science Data (PDS...,Data,‮⁤‭\n\nROSETTA-ORBITER 67P RSI 1/2/3 COMET ESC...,False,ROSETTA-ORBITER 67P RSI 1/2/3 COMET ESCORT 3 1...,"[[""ROSETTA-ORBITER"", 0.08596317751626563], [""6..."
538752,/SDE/PDS_API_Legacy_All/|f18951475dc5d738db366...,None,MARS EXPRESS MARS MRS 1/2/3 EXTENDED MISSION 7...,/SDE/PDS_API_Legacy_All/,/Planetary Science/Planetary Science Data (PDS...,Data,‮⁤‭\n\nMARS EXPRESS MARS MRS 1/2/3 EXTENDED MI...,False,MARS EXPRESS MARS MRS 1/2/3 EXTENDED MISSION 7...,"[[""MARS"", 0.06229927406458491], [""EXPRESS"", 0...."
538753,/SDE/PDS_API_Legacy_All/|5541e253d6e8f18807c0b...,None,ROSETTA-ORBITER 67P RSI 1/2/3 PRELANDING 0189 ...,/SDE/PDS_API_Legacy_All/,/Planetary Science/Planetary Science Data (PDS...,Data,‮⁤‭\n\nROSETTA-ORBITER 67P RSI 1/2/3 PRELANDIN...,False,ROSETTA-ORBITER 67P RSI 1/2/3 PRELANDING 0189 ...,"[[""ROSETTA-ORBITER"", 0.08596317751626563], [""6..."
538754,/SDE/PDS_API_Legacy_All/|112112698d27a449273b9...,None,MARS EXPRESS MARS MRS 1/2/3 EXTENDED MISSION 7...,/SDE/PDS_API_Legacy_All/,/Planetary Science/Planetary Science Data (PDS...,Data,‮⁤‭\n\nMARS EXPRESS MARS MRS 1/2/3 EXTENDED MI...,False,MARS EXPRESS MARS MRS 1/2/3 EXTENDED MISSION 7...,"[[""MARS"", 0.06229927406458491], [""EXPRESS"", 0...."
538755,/SDE/PDS_API_Legacy_All/|057a3ad392887bbb11cef...,None,ROSETTA-ORBITER 67P RSI 1/2/3 COMET ESCORT 1 0...,/SDE/PDS_API_Legacy_All/,/Planetary Science/Planetary Science Data (PDS...,Data,‮⁤‭\n\nROSETTA-ORBITER 67P RSI 1/2/3 COMET ESC...,False,ROSETTA-ORBITER 67P RSI 1/2/3 COMET ESCORT 1 0...,"[[""ROSETTA-ORBITER"", 0.08596317751626563], [""6..."

In [58]:
pds["n_words"] = pds["old_text"].apply(lambda x: len(x.split(" ")))

/tmp/ipykernel_2035512/3845714019.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pds["n_words"] = pds["old_text"].apply(lambda x: len(x.split(" ")))

In [59]:
pds["n_words"].describe()

count    6966.000000
mean        7.945019
std         1.812216
min         3.000000
25%         7.000000
50%         8.000000
75%         9.000000
max        22.000000
Name: n_words, dtype: float64

In [57]:
pds[pds["n_char"] == pds["n_char"].max()].iloc[0]["old_text"]

'\u202e\u2064\u202d\n\nCommercial Lunar Payload Services TO2 AB Peregrine-1 (CLPS TO2 AB Peregrine-1): Near-Infrared Volatiles Spectrometer System Longwave Calibration Sensor (NIRVSS_LCS) Bundle\n\n'

In [12]:
import pandas as pd

df = pd.read_csv("/rhome/sawale/indus_traning/sentense_transformers/data/PDS/dev_sde_index_pds_3_and_4_dump_2025-06-12.csv", sep="༜")

df.shape

/tmp/ipykernel_2051886/2090179711.py:3: ParserWarning: Falling back to the 'python' engine because the separator encoded in utf-8 is > 1 char long, and the 'c' engine does not support such separators; you can avoid this warning by specifying engine='python'.
  df = pd.read_csv("/rhome/sawale/indus_traning/sentense_transformers/data/PDS/dev_sde_index_pds_3_and_4_dump_2025-06-12.csv", sep="༜")

(163732, 276)

In [13]:
df.head()

,chunkid,databaseid,databasealias,documentweight,id,documentlanguages,treepath,title,filename,authors,...,enginecsv1,enginecsv2,enginecsv3,enginecsv4,engineusercsv1,engineusercsv2,engineusercsv3,engineusercsv4,enginestr1,enginestr2
0,538472,2,sde_index,default,/SDE/PDS_API_Legacy_All/|241566d5d0eb7afb30ef4...,en,/Planetary Science/Planetary Science Data (PDS...,ROSETTA-ORBITER CAL RPCMIP 3 CR5 V1.0,file.htm,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,538473,2,sde_index,default,/SDE/PDS_API_Legacy_All/|f25862eed648d0ce58521...,en,/Planetary Science/Planetary Science Data (PDS...,ROSETTA-ORBITER 67P RSI 1/2/3 COMET ESCORT 3 1...,file.htm,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,538474,2,sde_index,default,/SDE/PDS_API_Legacy_All/|f18951475dc5d738db366...,en,/Planetary Science/Planetary Science Data (PDS...,MARS EXPRESS MARS MRS 1/2/3 EXTENDED MISSION 7...,file.htm,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,538475,2,sde_index,default,/SDE/PDS_API_Legacy_All/|4a0990fc4c6c9dc7ea9de...,en,/Planetary Science/Planetary Science Data (PDS...,LP MAGER SPINAVG MAGNETIC FIELD LUNAR COORDS 5...,file.htm,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,538476,2,sde_index,default,/SDE/PDS_API_Legacy_All/|057a3ad392887bbb11cef...,en,/Planetary Science/Planetary Science Data (PDS...,ROSETTA-ORBITER 67P RSI 1/2/3 COMET ESCORT 1 0...,file.htm,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df["sourcestr6"].isna().sum()

np.int64(158450)

In [8]:
df.shape

(163732, 7)

In [ ]:
import pandas as pd
pds = pd.read_csv("/rhome/sawale/indus_traning/sentense_transformers/data/PDS/dev_sde_index_pds_3_and_4_dump_2025-06-12.csv", sep="༜")

file = open("rext.txt", "w")

for c in pds.columns:
    # search "Mars" in column
    for v in pds[c].to_list():
        if "Mars" in str(v):
            print(f"Found '	Mars`' in column {c}: {v}", file=file)

TypeError: read_csv() got an unexpected keyword argument 'columns'

In [13]:
pds["sourcecsv5"].value_counts()

sourcecsv5
Earth;Planet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    4598
65803 Didymos;Asteroid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2306
Laboratory Analog Jupiter;Laboratory Analog Saturn;Laboratory Analog Titan;Laboratory Analog                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     261
Saturn;Planet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    185
BIAS;Calibrator                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  174
Published Data;Laboratory Analog                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 142
DOME FLAT;Calibrator                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             107
Mars;Planet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      105
Mercury;Planet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    58
Sky;Calibration Field                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             11
(134340) Pluto;26 Tauri;3 Centauri;78 Tauri;Aegaeon;Albiorix;Aldebaran;Algol;Alpha Arae;Alpha Centauri;Alpha Crucis;Alpha Eridani;Alpha Sextantis;Alpha Trianguli Australis;Antares;Anthe;Arcturus;Atlas;Bebhionn;Bergelmir;Bestla;Beta Canis Majoris;Beta Centauri;Beta Crucis;Beta Librae;Beta Lupi;Beta Orionis;Beta Sagittarii;Betelgeuse;CW Leonis;Cal Lamps;Calypso;Canopus;Capella;Chi Centauri;Daphnis;Delta Aquarii;Delta Centauri;Delta Lupi;Delta Persei;Delta Virginis;Dione;Earth;Enceladus;Epimetheus;Epsilon Cassiopeiae;Epsilon Centauri;Epsilon Lupi;Epsilon Orionis;Epsilon Piscis Austrini;Erriapus;Eta Carinae;Eta Lupi;Eta Ursae Majoris;Fomalhaut;Fornjot;Gamma Arae;Gamma Cassiopeiae;Gamma Columbae;Gamma Crucis;Gamma Gruis;Gamma Lupi;Gamma Pegasi;Greip;HD 71334;HR 996;Hati;Helene;Hyperion;Hyrrokkin;Iapetus;Ijiraq;Iota Centauri;Janus;Jarnsaxa;Jupiter;Kappa Centauri;Kappa Orionis;Kari;Kiviuq;Lambda Ceti;Lambda Scorpii;Loge;Methone;Mimas;Mu Piscis Austrini;Mundilfari;Narvi;Nu Centauri;Omicron Ceti;Paaliaq;Pallene;Pan;Pandora;Phoebe;Polydeuces;Probe;Procyon;Prometheus;Psi Centauri;R Cassiopeiae;R Hydrae;R Leo;Regulus;Rhea;S/2004 S 12;S/2004 S 13;Saturn Rings;Saturn;Scat Light;Siarnaq;Sirius;Skathi;Skoll;Sky;Spica;Star;Sun;Surtur;Suttungr;Tarqeq;Tarvos;Telesto;Tethys;Theta Arae;Theta Hydrae;Thrymr;Titan;Unknown;Vega;W Hydrae;Ymir;Zeta Canis Majoris;Zeta Centauri;Zeta Ophiuchi;Zeta Orionis;Zeta Persei;Dwarf Planet;Satellite;Calibrator;Planet;Equipment;Ring;Calibration Field       2
Name: count, dtype: int64

In [14]:
pds["sourcecsv5"].isna().sum()

155783

In [11]:
pds["sourcestr6"].value_counts()

sourcestr6
Results that have been distilled from one or more calibrated data products (for example, maps, gravity or magnetic fields, or ring particle size distributions). Supplementary data, such as calibration tables or tables of viewing geometry, used to interpret observational data should also be classified as 'derived' data if not easily matched to one of the other three categories.    4976
Original data from an instrument. If compression, reformatting, packetization, or other translation has been applied to facilitate data transmission or storage, those processes will be reversed so that the archived data are in a PDS approved archive format.                                                                                                                               253
Data converted to physical units, which makes values independent of the instrument.                                                                                                                                                                                                                                                                                                              53
Name: count, dtype: int64

In [12]:
pds["sourcestr6"].isna().sum()

158450

In [19]:
pds["title"].nunique()

158539